name = "RandomNumbers"
uuid = "e6cf234a-135c-5ec9-84dd-332b85af5143"
author = ["Sunoru <s@sunoru.com>"]
repo = "https://github.com/sunoru/RandomNumbers.jl.git"
version = "1.2.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
